name: Publish to npm

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write # necessario para provenance

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - name: Verify npm authentication
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_DEV }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test:ci
      - run: pnpm build
      - run: pnpm publish --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_DEV }}
